### ISSUE TITLE
Format numbers by configuration

### ISSUE THREAD

**Issue by SrBedrock** [hyperdefined/ToolStats#24]
Add possibility to format numbers as it was done with dates.

Example: 1,000 (USA format) = 1.000 (BR format)

**Comment by hyperdefined** [comment]
The format should automatically change depending on the server's location and language. I use whatever Locale Java detects. I could in theory add support for setting your own. I could also add support for setting your own format to be whatever you want, as Java also let's you hardcode it. But that requires you to know how that works. It's definitely something I can look into when I have time.

**Comment by hyperdefined** [comment]
Interesting, that's how I would of done it myself too. What plugin is that?

**Comment by hyperdefined** [comment]
After some testing, I believe this would be a good solution:
```yaml
number-formats:
  comma: ","
  decimal: "."
```
It seems like changing the format you mentioned above does not let the user change the symbol separator. However, I can use this instead to change the decimal & comma separator.

I could add support for changing the format as above, but this would be a solution to changing to BR format.

**Comment by hyperdefined** [comment]
Here's another update. This is how the config values would look:
```yaml
number-formats:
  comma-separator: ","
  decimal-separator: "."
  comma-format: "#,###"
  decimal-format: "#,###.00"
```
This let's you set the format and the separators. I think this would allow for the best customization.
